version: "3.7"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/dev/client.Dockerfile
    volumes:
      - web-content:/client/build

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/dev/server.Dockerfile
    depends_on:
      - postgresql

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./docker/dev/proxy.Dockerfile
    volumes:
      - web-content:/content
    ports:
      - "80:80"
    depends_on:
      - client
      - api

  postgresql:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teacher_reviewer
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    container_name: db-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgresql

volumes:
  postgres:
  web-content:
