version: "3.7"

services:
  client:
    container_name: client
    image: node:14.17-alpine
    depends_on:
      - api
      - mariadb
    command: >
      sh -c "yarn &&
          yarn start"
    ports:
      - 3000:3000
    working_dir: /app/client
    volumes:
      - ../client/:/app/client

  api:
    container_name: api
    image: node:14.17-alpine
    depends_on:
      - mariadb
    command: >
      sh -c "yarn &&
          yarn start:dev"
    ports:
      - 5000:5000
    working_dir: /app/server
    volumes:
      - ../server/:/app/server

  postgresql:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgresql

volumes:
  postgres:
