version: "3.7"

services:
  client:
    container_name: client
    image: node:14.17-alpine
    depends_on:
      - api
      - mariadb
    command: >
      sh -c "yarn &&
          yarn start"
    ports:
      - 3000:3000
    working_dir: /app/client
    volumes:
      - ../client/:/app/client

  api:
    container_name: api
    image: node:14.17-alpine
    depends_on:
      - mariadb
    command: >
      sh -c "yarn &&
          yarn start:dev"
    ports:
      - 5000:5000
    working_dir: /app/server
    volumes:
      - ../server/:/app/server

  mariadb:
    container_name: database
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: teacher_reviewer
    ports:
      - 3307:3306
    volumes:
      - maria:/data/db

volumes:
  maria:
